# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cipher.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        MainWindow.setFont(font)
        MainWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 900, 700))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/newPrefix/background.png"))
        self.background.setObjectName("background")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(380, 20, 501, 661))
        self.stackedWidget.setObjectName("stackedWidget")
        self.normal = QtWidgets.QWidget()
        self.normal.setObjectName("normal")
        self.text_label = QtWidgets.QLabel(self.normal)
        self.text_label.setGeometry(QtCore.QRect(40, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.text_label.setFont(font)
        self.text_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.text_label.setObjectName("text_label")
        self.text_input = QtWidgets.QLineEdit(self.normal)
        self.text_input.setGeometry(QtCore.QRect(170, 70, 291, 31))
        self.text_input.setStyleSheet("border: 1px solid #0C145A;\n"
"box-sizing: border-box;\n"
"")
        self.text_input.setObjectName("text_input")
        self.title = QtWidgets.QLabel(self.normal)
        self.title.setGeometry(QtCore.QRect(0, 10, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"color:#0C145A;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.register_button = QtWidgets.QPushButton(self.normal)
        self.register_button.setGeometry(QtCore.QRect(130, 590, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.register_button.setFont(font)
        self.register_button.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #4D17E2;\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);")
        self.register_button.setObjectName("register_button")
        self.key_label = QtWidgets.QLabel(self.normal)
        self.key_label.setGeometry(QtCore.QRect(40, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.key_label.setFont(font)
        self.key_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.key_label.setObjectName("key_label")
        self.key_input = QtWidgets.QLineEdit(self.normal)
        self.key_input.setGeometry(QtCore.QRect(170, 110, 291, 31))
        self.key_input.setStyleSheet("border: 1px solid #0C145A;\n"
"box-sizing: border-box;\n"
"")
        self.key_input.setObjectName("key_input")
        self.upload_button = QtWidgets.QPushButton(self.normal)
        self.upload_button.setGeometry(QtCore.QRect(120, 160, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.upload_button.setFont(font)
        self.upload_button.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #E7EAF5;\n"
"border-radius: 10px;\n"
"color:#0C145A;")
        self.upload_button.setObjectName("upload_button")
        self.clear_button = QtWidgets.QPushButton(self.normal)
        self.clear_button.setGeometry(QtCore.QRect(270, 160, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #E7EAF5;\n"
"border-radius: 10px;\n"
"color:#0C145A;")
        self.clear_button.setObjectName("clear_button")
        self.mode_label = QtWidgets.QLabel(self.normal)
        self.mode_label.setGeometry(QtCore.QRect(40, 200, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.mode_label.setFont(font)
        self.mode_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.mode_label.setObjectName("mode_label")
        self.encrypt = QtWidgets.QRadioButton(self.normal)
        self.encrypt.setGeometry(QtCore.QRect(170, 200, 271, 20))
        self.encrypt.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"color:#0C145A;")
        self.encrypt.setObjectName("encrypt")
        self.decrypt = QtWidgets.QRadioButton(self.normal)
        self.decrypt.setGeometry(QtCore.QRect(170, 230, 271, 20))
        self.decrypt.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"color:#0C145A;")
        self.decrypt.setObjectName("decrypt")
        self.print_label = QtWidgets.QLabel(self.normal)
        self.print_label.setGeometry(QtCore.QRect(40, 260, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.print_label.setFont(font)
        self.print_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.print_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.print_label.setWordWrap(True)
        self.print_label.setObjectName("print_label")
        self.copy_button = QtWidgets.QPushButton(self.normal)
        self.copy_button.setGeometry(QtCore.QRect(120, 540, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.copy_button.setFont(font)
        self.copy_button.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #E7EAF5;\n"
"border-radius: 10px;\n"
"color:#0C145A;")
        self.copy_button.setObjectName("copy_button")
        self.save_button = QtWidgets.QPushButton(self.normal)
        self.save_button.setGeometry(QtCore.QRect(270, 540, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #E7EAF5;\n"
"border-radius: 10px;\n"
"color:#0C145A;")
        self.save_button.setObjectName("save_button")
        self.result_label = QtWidgets.QLabel(self.normal)
        self.result_label.setGeometry(QtCore.QRect(40, 320, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.result_label.setFont(font)
        self.result_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.result_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.result_label.setWordWrap(True)
        self.result_label.setObjectName("result_label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.normal)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 360, 421, 161))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.widget = QtWidgets.QWidget(self.normal)
        self.widget.setGeometry(QtCore.QRect(170, 250, 241, 80))
        self.widget.setObjectName("widget")
        self.five_input = QtWidgets.QRadioButton(self.widget)
        self.five_input.setGeometry(QtCore.QRect(0, 40, 271, 20))
        self.five_input.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"color:#0C145A;")
        self.five_input.setObjectName("five_input")
        self.space_input = QtWidgets.QRadioButton(self.widget)
        self.space_input.setGeometry(QtCore.QRect(0, 10, 271, 20))
        self.space_input.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"color:#0C145A;")
        self.space_input.setObjectName("space_input")
        self.stackedWidget.addWidget(self.normal)
        self.sign_in = QtWidgets.QWidget()
        self.sign_in.setEnabled(True)
        self.sign_in.setObjectName("sign_in")
        self.title_2 = QtWidgets.QLabel(self.sign_in)
        self.title_2.setGeometry(QtCore.QRect(0, 10, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.title_2.setFont(font)
        self.title_2.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 20px;\n"
"line-height: 23px;\n"
"color:#0C145A;")
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.rotor_1 = QtWidgets.QSlider(self.sign_in)
        self.rotor_1.setGeometry(QtCore.QRect(170, 50, 22, 131))
        self.rotor_1.setStyleSheet("color:#0C145A;")
        self.rotor_1.setMaximum(25)
        self.rotor_1.setSingleStep(1)
        self.rotor_1.setOrientation(QtCore.Qt.Vertical)
        self.rotor_1.setInvertedAppearance(True)
        self.rotor_1.setInvertedControls(False)
        self.rotor_1.setObjectName("rotor_1")
        self.rotor_2 = QtWidgets.QSlider(self.sign_in)
        self.rotor_2.setGeometry(QtCore.QRect(240, 50, 22, 131))
        self.rotor_2.setStyleSheet("color:#0C145A;")
        self.rotor_2.setMaximum(25)
        self.rotor_2.setSingleStep(1)
        self.rotor_2.setOrientation(QtCore.Qt.Vertical)
        self.rotor_2.setInvertedAppearance(True)
        self.rotor_2.setInvertedControls(False)
        self.rotor_2.setObjectName("rotor_2")
        self.rotor_3 = QtWidgets.QSlider(self.sign_in)
        self.rotor_3.setGeometry(QtCore.QRect(310, 50, 22, 131))
        self.rotor_3.setStyleSheet("color:#0C145A;")
        self.rotor_3.setMaximum(25)
        self.rotor_3.setSingleStep(1)
        self.rotor_3.setOrientation(QtCore.Qt.Vertical)
        self.rotor_3.setInvertedAppearance(True)
        self.rotor_3.setInvertedControls(False)
        self.rotor_3.setObjectName("rotor_3")
        self.position_label = QtWidgets.QLabel(self.sign_in)
        self.position_label.setGeometry(QtCore.QRect(40, 210, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.position_label.setFont(font)
        self.position_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.position_label.setObjectName("position_label")
        self.rotor_1_label = QtWidgets.QLabel(self.sign_in)
        self.rotor_1_label.setGeometry(QtCore.QRect(170, 190, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.rotor_1_label.setFont(font)
        self.rotor_1_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.rotor_1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotor_1_label.setObjectName("rotor_1_label")
        self.rotor_2_label = QtWidgets.QLabel(self.sign_in)
        self.rotor_2_label.setGeometry(QtCore.QRect(240, 190, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.rotor_2_label.setFont(font)
        self.rotor_2_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.rotor_2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotor_2_label.setObjectName("rotor_2_label")
        self.rotor_3_label = QtWidgets.QLabel(self.sign_in)
        self.rotor_3_label.setGeometry(QtCore.QRect(310, 190, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.rotor_3_label.setFont(font)
        self.rotor_3_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.rotor_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotor_3_label.setObjectName("rotor_3_label")
        self.key_input_3 = QtWidgets.QLineEdit(self.sign_in)
        self.key_input_3.setGeometry(QtCore.QRect(170, 280, 291, 31))
        self.key_input_3.setStyleSheet("border: 1px solid #0C145A;\n"
"box-sizing: border-box;\n"
"")
        self.key_input_3.setObjectName("key_input_3")
        self.upload_button_3 = QtWidgets.QPushButton(self.sign_in)
        self.upload_button_3.setGeometry(QtCore.QRect(120, 330, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.upload_button_3.setFont(font)
        self.upload_button_3.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #E7EAF5;\n"
"border-radius: 10px;\n"
"color:#0C145A;")
        self.upload_button_3.setObjectName("upload_button_3")
        self.clear_button_3 = QtWidgets.QPushButton(self.sign_in)
        self.clear_button_3.setGeometry(QtCore.QRect(270, 330, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.clear_button_3.setFont(font)
        self.clear_button_3.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #E7EAF5;\n"
"border-radius: 10px;\n"
"color:#0C145A;")
        self.clear_button_3.setObjectName("clear_button_3")
        self.text_label_3 = QtWidgets.QLabel(self.sign_in)
        self.text_label_3.setGeometry(QtCore.QRect(40, 240, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.text_label_3.setFont(font)
        self.text_label_3.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.text_label_3.setObjectName("text_label_3")
        self.key_label_3 = QtWidgets.QLabel(self.sign_in)
        self.key_label_3.setGeometry(QtCore.QRect(40, 280, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.key_label_3.setFont(font)
        self.key_label_3.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.key_label_3.setObjectName("key_label_3")
        self.text_input_3 = QtWidgets.QLineEdit(self.sign_in)
        self.text_input_3.setGeometry(QtCore.QRect(170, 240, 291, 31))
        self.text_input_3.setStyleSheet("border: 1px solid #0C145A;\n"
"box-sizing: border-box;\n"
"")
        self.text_input_3.setObjectName("text_input_3")
        self.save_button_3 = QtWidgets.QPushButton(self.sign_in)
        self.save_button_3.setGeometry(QtCore.QRect(270, 540, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.save_button_3.setFont(font)
        self.save_button_3.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #E7EAF5;\n"
"border-radius: 10px;\n"
"color:#0C145A;")
        self.save_button_3.setObjectName("save_button_3")
        self.result_label_3 = QtWidgets.QLabel(self.sign_in)
        self.result_label_3.setGeometry(QtCore.QRect(40, 340, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.result_label_3.setFont(font)
        self.result_label_3.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;")
        self.result_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.result_label_3.setWordWrap(True)
        self.result_label_3.setObjectName("result_label_3")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.sign_in)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(40, 380, 421, 141))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.register_button_3 = QtWidgets.QPushButton(self.sign_in)
        self.register_button_3.setGeometry(QtCore.QRect(130, 590, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.register_button_3.setFont(font)
        self.register_button_3.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #4D17E2;\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);")
        self.register_button_3.setObjectName("register_button_3")
        self.copy_button_3 = QtWidgets.QPushButton(self.sign_in)
        self.copy_button_3.setGeometry(QtCore.QRect(120, 540, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.copy_button_3.setFont(font)
        self.copy_button_3.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #E7EAF5;\n"
"border-radius: 10px;\n"
"color:#0C145A;")
        self.copy_button_3.setObjectName("copy_button_3")
        self.stackedWidget.addWidget(self.sign_in)
        self.register_button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.register_button_4.setGeometry(QtCore.QRect(80, 350, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.register_button_4.setFont(font)
        self.register_button_4.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #E7EAF5;\n"
"border-radius: 10px;\n"
"color:rgb(0, 0, 0);")
        self.register_button_4.setObjectName("register_button_4")
        self.register_button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.register_button_5.setGeometry(QtCore.QRect(80, 390, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.register_button_5.setFont(font)
        self.register_button_5.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #4D17E2;\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);")
        self.register_button_5.setObjectName("register_button_5")
        self.register_button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.register_button_6.setGeometry(QtCore.QRect(80, 430, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.register_button_6.setFont(font)
        self.register_button_6.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #4D17E2;\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);")
        self.register_button_6.setObjectName("register_button_6")
        self.register_button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.register_button_7.setGeometry(QtCore.QRect(80, 470, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.register_button_7.setFont(font)
        self.register_button_7.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 16px;\n"
"background: #4D17E2;\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);")
        self.register_button_7.setObjectName("register_button_7")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Enigma\'s Cipher"))
        self.text_label.setText(_translate("MainWindow", "Enter message:"))
        self.title.setText(_translate("MainWindow", "Vigenere Cipher"))
        self.register_button.setText(_translate("MainWindow", "Run"))
        self.key_label.setText(_translate("MainWindow", "Enter key:"))
        self.upload_button.setText(_translate("MainWindow", "Open File"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.mode_label.setText(_translate("MainWindow", "Choose mode:"))
        self.encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.print_label.setText(_translate("MainWindow", "Choose print option:"))
        self.copy_button.setText(_translate("MainWindow", "Copy result"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.result_label.setText(_translate("MainWindow", "Result:"))
        self.five_input.setText(_translate("MainWindow", "Seperated every 5 character"))
        self.space_input.setText(_translate("MainWindow", "Without Space"))
        self.title_2.setText(_translate("MainWindow", "Enigma Cipher"))
        self.position_label.setText(_translate("MainWindow", "Position:"))
        self.rotor_1_label.setText(_translate("MainWindow", "A"))
        self.rotor_2_label.setText(_translate("MainWindow", "A"))
        self.rotor_3_label.setText(_translate("MainWindow", "A"))
        self.upload_button_3.setText(_translate("MainWindow", "Open File"))
        self.clear_button_3.setText(_translate("MainWindow", "Clear"))
        self.text_label_3.setText(_translate("MainWindow", "Enter message:"))
        self.key_label_3.setText(_translate("MainWindow", "Enter key:"))
        self.save_button_3.setText(_translate("MainWindow", "Save"))
        self.result_label_3.setText(_translate("MainWindow", "Result:"))
        self.register_button_3.setText(_translate("MainWindow", "Run"))
        self.copy_button_3.setText(_translate("MainWindow", "Copy result"))
        self.register_button_4.setText(_translate("MainWindow", "Vigenere Cipher"))
        self.register_button_5.setText(_translate("MainWindow", "Extended Vigenere Cipher"))
        self.register_button_6.setText(_translate("MainWindow", "Playfair Cipher"))
        self.register_button_7.setText(_translate("MainWindow", "Enigma Cipher"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
